<!doctype html>
<html>
<head>
  <title>html - yangaron</title>
  <meta charset="utf-8">
</head>
<body>
<h1><a href="index.html">WEB</a></h1>
<ul>
  <li><a href="1.HTML">1.HTML</a></li>
  <li><a href="2.CS">2.CSS</a></li>
  <li><a href="3.Javascript">3.JavaScript</a></li>
</ul>
<h2>2.CSS</h2>
<br>
<a href="http://news.jtbc.joins.com/article/article.aspx?news_id=NB11922411" target="_blank">CSSSSSSCSCSCSCS</a>
<img src="html.jpg" width="100%">
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/50JOpxN0554" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://html-yangaron.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</body>
</html>
